name: Run tests

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: true
            matrix:
                os: [ 'ubuntu-latest' ]
                php: [ '7.2', '7.3', '7.4', '8.0' ]

        name: Run tests on PHP ${{ matrix.php }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    coverage: none

            -   name: Install dependencies
                run: composer install --no-interaction

            -   name: Run tests
                run: vendor/bin/phpunit
