name: Tests

on:
    push:
    pull_request:
    schedule:
        -   cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ 'ubuntu-latest' ]
                php: [ '7.2', '7.3', '7.4', '8.0' ]
                laravel: [ '6.*', '7.*', '8.*' ]
                include:
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: 7.*
                        testbench: 5.*
                    -   laravel: 6.*
                        testbench: 4.*
                exclude:
                    -   laravel: 8.*
                        php: 7.2

        name: PHP ${{ matrix.php }}, Laravel ${{ matrix.laravel }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Cache dependencies
                uses: actions/cache@v2
                with:
                    path: ~/.composer/cache/files
                    key: dependencies-laravel-${{ matrix.laravel }}-php-${{ matrix.php }}-composer-${{ hashFiles('composer.json') }}

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: fileinfo, pdo, pdo_sqlite
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "illuminate/database:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --prefer-dist --no-interaction --no-progress --no-update
                    composer update --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit --coverage-clover=coverage.xml

            -   name: Code coverage
                run: "bash <(curl -s https://codecov.io/bash) || true"
