name: Tests

on:
    push:
    pull_request:
    schedule:
        - cron: '0 0 * * *'

jobs:
    tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [ 'ubuntu-latest', 'windows-latest' ]
                php: [ '7.2', '7.3', '7.4', '8.0' ]
                laravel: [ '6.*', '7.*', '8.*' ]
                include:
                    -   laravel: 8.*
                        testbench: 6.*
                    -   laravel: 7.*
                        testbench: 5.*
                    -   laravel: 6.*
                        testbench: 4.*
                exclude:
                    -   laravel: 8.*
                    -   php: 7.2

        name: Run tests on PHP ${{ matrix.php }} - Laravel ${{ matrix.laravel }} - OS ${{ matrix.os }}

        steps:
            -   name: Checkout code
                uses: actions/checkout@v2

            -   name: Setup PHP
                uses: shivammathur/setup-php@v2
                with:
                    php-version: ${{ matrix.php }}
                    extensions: fileinfo, pdo, pdo_sqlite
                    coverage: none

            -   name: Install dependencies
                run: |
                    composer require "illuminate/database:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" --no-interaction --no-update
                    composer update --no-interaction

            -   name: Execute tests
                run: vendor/bin/phpunit
